complete -c gwa -x -a "(__fish_git_branches)" -d "Branch name"
complete -c gwd -d "Remove worktree and branch"
complete -c gwl -d "List all worktrees"
complete -c gwcd -x -a "(__fish_git_branches)" -d "Navigate to worktree or base"
complete -c gw -l with -a "tmux zellij code cursor nvim cd" -d "Command to open the worktree"
